sudo: required

language: python

services:
  - docker

before_install:
 - docker pull giacomov/hawc-docker
 - docker ps -a
 - ls $TRAVIS_BUILD_DIR


script:
 - docker run --rm -it -u `id -u` -v $TRAVIS_BUILD_DIR:/home/hawc/workdir giacomov/hawc-docker /bin/bash --login -c "cd /home/hawc/workdir && export HOME=`pwd` && source test_inside_docker.sh"
#after_success:
# - coveralls #--config_file .coveragerc