parallel:
  
  #Name of the ipython profile to use for parallel
  #computing (see IPython documentation). Leave it
  #to "default" if you didn't configure any other
  #profile
  
  IPython profile name: default
  
  #Set this to True if you want to always execute
  #computation in parallel, without the use of the
  # "with parallel_computation:" construct. To False
  #otherwise (default: False)
  
  use-parallel: False

ogip:

  data plot cmap: rainbow

  model plot cmap: gnuplot

  counts color: '#377eb8'

  background color: '#e41a1c'

