package:
  name: cthreeml
  version: "1.0.3"

source:
  git_url: https://github.com/giacomov/cthreeML.git

requirements:
  build:
    - python
    - setuptools
    - gcc
    - libgcc
    - boost
    - numpy

  run:
    - python
    - libgcc
    - boost
    - numpy

test:
  imports:
    - cthreeML

about:
  home: https://github.com/giacomov/cthreeML
  license: BSD-3
  summary: 'The C/C++ bridge for the Multi-Mission Maximum Likelihood framework (github.com/giacomov/3ML)'
  license_family: BSD

