{% set name = "html2text" %}
{% set version = "2016.9.19" %}
{% set hash_type = "sha256" %}
{% set hash_value = "554ef5fd6c6cf6e3e4f725a62a3e9ec86a0e4d33cd0928136d1c79dbeb7b2d55" %}

package:
  version: '{{ version }}'
  name: '{{ name|lower }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'
  fn: '{{ name }}-{{ version }}.tar.gz'

build:
  entry_points:
    - html2text=html2text.cli:main
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  run:
    - python x.x
    - setuptools
  build:
    - python x.x
    - setuptools

test:
  imports:
    - html2text
  commands:
    - html2text --help

about:
  dev_url: ''
  description: "Turn HTML into equivalent Markdown-structured text."
  license: GNU General Public License (GPL)
  license_family: LGPL
  summary: Turn HTML into equivalent Markdown-structured text.
  home: https://github.com/Alir3z4/html2text/
  license_file: ''
  doc_url: ''

extra:
  recipe-maintainers:
    - giacomov
